Create did doc test added
knox-networks/ssi pull request #78
Opened 2022-10-20 21:46 UTC by sKudryashov

2022-10-20 23:54 UTC, LuisOsta requested changes

2022-10-20 23:54 UTC, LuisOsta commented on core/src/identity.rs
> +    #[ignore]
You should remove this `#[ignore]`

2022-10-21 00:03 UTC, LuisOsta requested changes

2022-10-21 00:03 UTC, LuisOsta commented on core/src/identity.rs
> +        let kp = signature::suite::ed25519_2020::Ed25519KeyPair::new(None).unwrap();
So if we are going to do a structural comparison vs a complete comparison we should make it clear that the expectation json is a template and not an actual DID Document itself

2022-10-21 00:04 UTC, LuisOsta commented on core/src/identity.rs
> +        let kp = signature::suite::ed25519_2020::Ed25519KeyPair::new(None).unwrap();
Alternatively we can do a complete comparison by making the mnemonic fixed and restoring the KeyPair from that (instead of creating a new one

2022-10-21 14:09 UTC, mkatychev approved these changes

2022-10-21 16:14 UTC, LuisOsta approved these changes

2022-10-21 16:24 UTC, merged